//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnrealMacroGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>AdvancedDisplay</string>
  <string>AssetRegistrySearchable</string>
  <string>BlueprintAssignable</string>
  <string>BlueprintAuthorityOnly</string>
  <string>BlueprintCallable</string>
  <string>BlueprintReadOnly</string>
  <string>BlueprintReadWrite</string>
  <string>Config</string>
  <string>DuplicateTransient</string>
  <string>EditAnywhere</string>
  <string>EditDefaultsOnly</string>
  <string>EditFixedSize</string>
  <string>EditInline</string>
  <string>EditInstanceOnly</string>
  <string>Export</string>
  <string>GlobalConfig</string>
  <string>Instanced</string>
  <string>Interp</string>
  <string>Localized</string>
  <string>Native</string>
  <string>NoClear</string>
  <string>NoExport</string>
  <string>NonPIEDuplicateTransient</string>
  <string>NonTransactional</string>
  <string>NotReplicated</string>
  <string>Replicated</string>
  <string>RepRetry</string>
  <string>SaveGame</string>
  <string>SerializeText</string>
  <string>SkipSerialization</string>
  <string>SimpleDisplay</string>
  <string>TextExportTransient</string>
  <string>Transient</string>
  <string>VisibleAnywhere</string>
  <string>VisibleDefaultsOnly</string>
  <string>VisibleInstanceOnly</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UPROPERTY_MacroSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UPROPERTY_MacroSpecifiers"]));
            }
            set {
                this["UPROPERTY_MacroSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>BlueprintGetter</string>
  <string>BlueprintSetter</string>
  <string>Category</string>
  <string>ReplicatedUsing</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UPROPERTY_AdvancedSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UPROPERTY_AdvancedSettings"]));
            }
            set {
                this["UPROPERTY_AdvancedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>AllowAbstract;Bool</string>\r\n  <string>AllowedClasses;String</string>\r\n  <" +
            "string>AllowPreserveRatio;NoInput</string>\r\n  <string>ArrayClamp;String</string>" +
            "\r\n  <string>BlueprintBaseOnly;NoInput</string>\r\n  <string>BlueprintCompilerGener" +
            "atedDefaults;NoInput</string>\r\n  <string>ClampMin;Float</string>\r\n  <string>Clam" +
            "pMax;Float</string>\r\n  <string>ConfigHierarchyEditable;NoInput</string>\r\n  <stri" +
            "ng>ContentDir;NoInput</string>\r\n  <string>DisplayAfter;String</string>\r\n  <strin" +
            "g>DisplayName;String</string>\r\n  <string>DisplayPriority;Int</string>\r\n  <string" +
            ">DisplayThumbnail;Bool</string>\r\n  <string>EditCondition;String</string>\r\n  <str" +
            "ing>EditFixedOrder;NoInput</string>\r\n  <string>ExactClass;Bool</string>\r\n  <stri" +
            "ng>ExposeFunctionCategories;String</string>\r\n  <string>ExposeOnSpawn;Bool</strin" +
            "g>\r\n  <string>FilePathFilter;String</string>\r\n  <string>GetByRef;NoInput</string" +
            ">\r\n  <string>HideAlphaChannel;NoInput</string>\r\n  <string>HideViewOptions;NoInpu" +
            "t</string>\r\n  <string>InlineEditConditionToggle;NoInput</string>\r\n  <string>Long" +
            "PackageName;NoInput</string>\r\n  <string>MakeEditWidget;NoInput</string>\r\n  <stri" +
            "ng>NoGetter;NoInput</string>\r\n  <string>Bitmask;NoInput</string>\r\n  <string>Bitm" +
            "askEnum;String</string>\r\n  <string>ToolTip;String</string>\r\n  <string>ShortToolt" +
            "ip;String</string>\r\n  <string>ShowOnlyInnerProperties;NoInput</string>\r\n  <strin" +
            "g>UIMin;Float</string>\r\n  <string>UIMax;Float</string>\r\n  <string>AllowPrivateAc" +
            "cess;Bool</string>\r\n  <string>TitleProperty;String</string>\r\n  <string>MultiLine" +
            ";Bool</string>\r\n  <string>BindWidget;NoInput</string>\r\n  <string>BindWidgetOptio" +
            "nal;NoInput</string>\r\n  <string>BindWidgetAnimation;NoInput</string>\r\n  <string>" +
            "HideInDetailPanel;NoInput</string>\r\n  <string>ShowInnerProperties;NoInput</strin" +
            "g>\r\n  <string>FullyExpand;Bool</string>\r\n  <string>HideEditConditionToggle;NoInp" +
            "ut</string>\r\n  <string>EditConditionHides;NoInput</string>\r\n  <string>MaxPropert" +
            "yDepth;Int</string>\r\n  <string>ForceRebuildProperty;String</string>\r\n  <string>N" +
            "oResetToDefault;NoInput</string>\r\n  <string>NoSpinbox;Bool</string>\r\n  <string>S" +
            "liderExponent;Float</string>\r\n  <string>Delta;Float</string>\r\n  <string>Multiple" +
            ";Float</string>\r\n  <string>Units;String</string>\r\n  <string>ForceUnits;String</s" +
            "tring>\r\n  <string>GetOptions;String</string>\r\n  <string>PasswordField;Bool</stri" +
            "ng>\r\n  <string>ArraySizeEnum;NoInput</string>\r\n  <string>NoElementDuplicate;NoIn" +
            "put</string>\r\n  <string>NoClear;NoInput</string>\r\n  <string>ReadOnlyKeys;NoInput" +
            "</string>\r\n  <string>ForceInlineRow;NoInput</string>\r\n  <string>TransientToolPro" +
            "perty;NoInput</string>\r\n  <string>NonPIEDuplicateTransient;NoInput</string>\r\n  <" +
            "string>TextExportTransient;NoInput</string>\r\n  <string>MakeStructureDefaultValue" +
            ";String</string>\r\n  <string>DeprecatedProperty;NoInput</string>\r\n  <string>Depre" +
            "cationMessage;String</string>\r\n  <string>DisallowedClasses;String</string>\r\n  <s" +
            "tring>BindWidgetAnim;NoInput</string>\r\n  <string>BindWidgetAnimOptional;NoInput<" +
            "/string>\r\n  <string>DataTableImportOptional;Bool</string>\r\n  <string>RequiredAss" +
            "etDataTags;String</string>\r\n  <string>ConsoleVariable;String</string>\r\n  <string" +
            ">MetaClass;String</string>\r\n  <string>MustImplement;String</string>\r\n  <string>S" +
            "howTreeView;NoInput</string>\r\n  <string>OnlyPlaceable;NoInput</string>\r\n  <strin" +
            "g>AllowAnyActor;NoInput</string>\r\n  <string>UseComponentPicker;NoInput</string>\r" +
            "\n  <string>RelativePath;NoInput</string>\r\n  <string>RelativeToGameContentDir;NoI" +
            "nput</string>\r\n  <string>RelativeToGameDir;NoInput</string>\r\n  <string>ForceShow" +
            "EngineContent;NoInput</string>\r\n  <string>ForceShowPluginContent;NoInput</string" +
            ">\r\n  <string>ScriptNoExport;NoInput</string>\r\n  <string>ScriptName;NoInput</stri" +
            "ng>\r\n  <string>ConfigRestartRequired;Bool</string>\r\n  <string>Untracked;NoInput<" +
            "/string>\r\n  <string>AlwaysAsPin;NoInput</string>\r\n  <string>NeverAsPin;NoInput</" +
            "string>\r\n  <string>PinShownByDefault;NoInput</string>\r\n  <string>PinHiddenByDefa" +
            "ult;NoInput</string>\r\n  <string>CustomizeProperty;NoInput</string>\r\n  <string>Ov" +
            "erridingInputProperty;String</string>\r\n  <string>RequiredInput;Bool</string>\r\n  " +
            "<string>IgnoreForMemberInitializationTest;NoInput</string>\r\n  <string>FixedIncre" +
            "ment;Int</string>\r\n  <string>LatentCallbackTarget;NoInput</string>\r\n  <string>As" +
            "setBundles;String</string>\r\n  <string>XAxisName;String</string>\r\n  <string>YAxis" +
            "Name;String</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UPROPERTY_MetaSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UPROPERTY_MetaSpecifiers"]));
            }
            set {
                this["UPROPERTY_MetaSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>BlueprintAuthorityOnly</string>
  <string>BlueprintCallable</string>
  <string>BlueprintCosmetic</string>
  <string>BlueprintGetter</string>
  <string>BlueprintImplementableEvent</string>
  <string>BlueprintInternalUseOnly</string>
  <string>BlueprintNativeEvent</string>
  <string>BlueprintPure</string>
  <string>BlueprintSetter</string>
  <string>CallInEditor</string>
  <string>Client</string>
  <string>CustomThunk</string>
  <string>Exec</string>
  <string>NetMulticast</string>
  <string>Reliable</string>
  <string>SealedEvent</string>
  <string>ServiceRequest</string>
  <string>ServiceResponse</string>
  <string>Server</string>
  <string>Unreliable</string>
  <string>WithValidation</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UFUNCTION_MacroSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UFUNCTION_MacroSpecifiers"]));
            }
            set {
                this["UFUNCTION_MacroSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Category</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UFUNCTION_AdvancedSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UFUNCTION_AdvancedSettings"]));
            }
            set {
                this["UFUNCTION_AdvancedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>AdvancedDisplay;String</string>\r\n  <string>ArrayParm;String</string>\r\n  <s" +
            "tring>ArrayTypeDependentParams;String</string>\r\n  <string>AutoCreateRefTerm;Stri" +
            "ng</string>\r\n  <string>BlueprintAutocast;NoInput</string>\r\n  <string>BlueprintIn" +
            "ternalUseOnly;NoInput</string>\r\n  <string>BlueprintProtected;NoInput</string>\r\n " +
            " <string>CallableWithoutWorldContext;NoInput</string>\r\n  <string>CommutativeAsso" +
            "ciativeBinaryOperator;NoInput</string>\r\n  <string>CompactNodeTitle;String</strin" +
            "g>\r\n  <string>CustomStructureParam;String</string>\r\n  <string>DefaultToSelf;NoIn" +
            "put</string>\r\n  <string>DeprecatedFunction;NoInput</string>\r\n  <string>Deprecati" +
            "onMessage;String</string>\r\n  <string>DevelopmentOnly;NoInput</string>\r\n  <string" +
            ">DisplayName;String</string>\r\n  <string>ExpandEnumAsExecs;String</string>\r\n  <st" +
            "ring>HidePin;String</string>\r\n  <string>HideSelfPin;NoInput</string>\r\n  <string>" +
            "InternalUseParam;String</string>\r\n  <string>KeyWords;String</string>\r\n  <string>" +
            "Latent;NoInput</string>\r\n  <string>LatentInfo;String</string>\r\n  <string>Materia" +
            "lParameterCollectionFunction;NoInput</string>\r\n  <string>NativeBreakFunc;NoInput" +
            "</string>\r\n  <string>NotBlueprintThreadSafe;NoInput</string>\r\n  <string>ToolTip;" +
            "String</string>\r\n  <string>ShortTooltip;String</string>\r\n  <string>UnsafeDuringA" +
            "ctorConstruction;NoInput</string>\r\n  <string>WorldContext;String</string>\r\n  <st" +
            "ring>Variadic;NoInput</string>\r\n  <string>DeterminesOutputType;String</string>\r\n" +
            "  <string>DynamicOutputParam;String</string>\r\n  <string>ExpandBoolAsExecs;String" +
            "</string>\r\n  <string>AllowPrivateAccess;Bool</string>\r\n  <string>DataTablePin;St" +
            "ring</string>\r\n  <string>SetParam;String</string>\r\n  <string>MapParam;String</st" +
            "ring>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UFUNCTION_MetaSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UFUNCTION_MetaSpecifiers"]));
            }
            set {
                this["UFUNCTION_MetaSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Abstract</string>
  <string>AdvancedClassDisplay</string>
  <string>Blueprintable</string>
  <string>BlueprintType</string>
  <string>CollapseCategories</string>
  <string>Const</string>
  <string>ConversionRoot</string>
  <string>CustomConstructor</string>
  <string>DefaultToInstanced</string>
  <string>DependsOn</string>
  <string>Deprecated</string>
  <string>DontCollapseCategories</string>
  <string>EditInlineNew</string>
  <string>HideDropdown</string>
  <string>Intrinsic</string>
  <string>MinimalAPI</string>
  <string>NoExport</string>
  <string>NonTransient</string>
  <string>NotBlueprintable</string>
  <string>NotPlaceable</string>
  <string>PerObjectConfig</string>
  <string>Placeable</string>
  <string>Transient</string>
  <string>DefaultConfig</string>
  <string>ConfigDoNotCheckDefaults</string>
  <string>GlobalUserConfig</string>
  <string>ProjectUserConfig</string>
  <string>Experimental</string>
  <string>ComponentWrapperClass</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UCLASS_MacroSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UCLASS_MacroSpecifiers"]));
            }
            set {
                this["UCLASS_MacroSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>AutoCollapseCategories</string>
  <string>AutoExpandCategories</string>
  <string>ClassGroup</string>
  <string>Config</string>
  <string>DontAutoCollapseCategories</string>
  <string>HideCategories</string>
  <string>HideFunctions</string>
  <string>ShowCategories</string>
  <string>ShowFunctions</string>
  <string>Within</string>
  <string>ScriptName</string>
  <string>DependsOn</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UCLASS_AdvancedSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UCLASS_AdvancedSettings"]));
            }
            set {
                this["UCLASS_AdvancedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>BlueprintSpawnableComponent;NoInput</string>
  <string>BlueprintThreadSafe;NoInput</string>
  <string>ChildCannotTick;NoInput</string>
  <string>ChildCanTick;NoInput</string>
  <string>DeprecatedNode;NoInput</string>
  <string>DeprecationMessage;String</string>
  <string>DisplayName;String</string>
  <string>DontUseGenericSpawnObject;NoInput</string>
  <string>ExposedAsyncProxy;NoInput</string>
  <string>IgnoreCategoryKeywordsInSubclasses;NoInput</string>
  <string>IsBlueprintBase;Bool</string>
  <string>KismetHideOverrides;String</string>
  <string>ProhibitedInterfaces;String</string>
  <string>RestrictedToClasses;String</string>
  <string>ShortToolTip;String</string>
  <string>ShowWorldContextPin;NoInput</string>
  <string>UsesHierarchy;NoInput</string>
  <string>ToolTip;String</string>
  <string>PrioritizeCategories;String</string>
  <string>DisplayThumbnail;Bool</string>
  <string>IgnoreClassThumbnail;NoInput</string>
  <string>CommandLineID;String</string>
  <string>DisableNativeTick;NoInput</string>
  <string>EntryInterface;String</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UCLASS_MetaSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UCLASS_MetaSpecifiers"]));
            }
            set {
                this["UCLASS_MetaSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Atomic</string>
  <string>BlueprintType</string>
  <string>NoExport</string>
  <string>Immutable</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection USTRUCT_MacroSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["USTRUCT_MacroSpecifiers"]));
            }
            set {
                this["USTRUCT_MacroSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection USTRUCT_AdvancedSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["USTRUCT_AdvancedSettings"]));
            }
            set {
                this["USTRUCT_AdvancedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>BlueprintSpawnableComponent;NoInput</string>
  <string>BlueprintThreadSafe;NoInput</string>
  <string>ChildCannotTick;NoInput</string>
  <string>ChildCanTick;NoInput</string>
  <string>DeprecatedNode;NoInput</string>
  <string>DeprecationMessage;String</string>
  <string>DisplayName;String</string>
  <string>DontUseGenericSpawnObject;NoInput</string>
  <string>ExposedAsyncProxy;NoInput</string>
  <string>IgnoreCategoryKeywordsInSubclasses;NoInput</string>
  <string>IsBlueprintBase;Bool</string>
  <string>KismetHideOverrides;String</string>
  <string>ProhibitedInterfaces;String</string>
  <string>RestrictedToClasses;String</string>
  <string>ShortToolTip;String</string>
  <string>ShowWorldContextPin;NoInput</string>
  <string>UsesHierarchy;NoInput</string>
  <string>ToolTip;String</string>
  <string>HasNativeBreak;String</string>
  <string>HasNativeMake;String</string>
  <string>HiddenByDefault;NoInput</string>
  <string>DisableSplitPin;NoInput</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection USTRUCT_MetaSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["USTRUCT_MetaSpecifiers"]));
            }
            set {
                this["USTRUCT_MetaSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>BlueprintType</string>\r\n  <string>ScriptName</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UENUM_MacroSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UENUM_MacroSpecifiers"]));
            }
            set {
                this["UENUM_MacroSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Category</string>\r\n  <string>ToolTip</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UENUM_AdvancedSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UENUM_AdvancedSettings"]));
            }
            set {
                this["UENUM_AdvancedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Bitflags;NoInput</string>
  <string>Experimental;NoInput</string>
  <string>ScriptName;String</string>
  <string>ToolTip;String</string>
  <string>UseEnumValuesAsMaskValuesInEditor;Bool</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UENUM_MetaSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UENUM_MetaSpecifiers"]));
            }
            set {
                this["UENUM_MetaSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Blueprintable</string>
  <string>NoBlueprintable</string>
  <string>MinimalAPI</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UINTERFACE_MacroSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UINTERFACE_MacroSpecifiers"]));
            }
            set {
                this["UINTERFACE_MacroSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UINTERFACE_AdvancedSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UINTERFACE_AdvancedSettings"]));
            }
            set {
                this["UINTERFACE_AdvancedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>CannotImplementInterfaceInBlueprint;NoInput</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UINTERFACE_MetaSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UINTERFACE_MetaSpecifiers"]));
            }
            set {
                this["UINTERFACE_MetaSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UMETA_MacroSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UMETA_MacroSpecifiers"]));
            }
            set {
                this["UMETA_MacroSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UMETA_AdvancedSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UMETA_AdvancedSettings"]));
            }
            set {
                this["UMETA_AdvancedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>DisplayName;String</string>
  <string>Hidden;NoInput</string>
  <string>ToolTip;String</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UMETA_MetaSpecifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UMETA_MetaSpecifiers"]));
            }
            set {
                this["UMETA_MetaSpecifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>LogTemp</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UE_LOG_LogCategory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UE_LOG_LogCategory"]));
            }
            set {
                this["UE_LOG_LogCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://benui.ca/unreal/uproperty/")]
        public string UPROPERTY_Document {
            get {
                return ((string)(this["UPROPERTY_Document"]));
            }
            set {
                this["UPROPERTY_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://benui.ca/unreal/ufunction/")]
        public string UFUNCTION_Document {
            get {
                return ((string)(this["UFUNCTION_Document"]));
            }
            set {
                this["UFUNCTION_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://benui.ca/unreal/uclass/")]
        public string UCLASS_Document {
            get {
                return ((string)(this["UCLASS_Document"]));
            }
            set {
                this["UCLASS_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://benui.ca/unreal/ustruct/")]
        public string USTRUCT_Document {
            get {
                return ((string)(this["USTRUCT_Document"]));
            }
            set {
                this["USTRUCT_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://benui.ca/unreal/uenum-umeta/")]
        public string UENUM_Document {
            get {
                return ((string)(this["UENUM_Document"]));
            }
            set {
                this["UENUM_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UINTERFACE_Document {
            get {
                return ((string)(this["UINTERFACE_Document"]));
            }
            set {
                this["UINTERFACE_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://benui.ca/unreal/uenum-umeta/")]
        public string UMETA_Document {
            get {
                return ((string)(this["UMETA_Document"]));
            }
            set {
                this["UMETA_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.unrealengine.com/en-US/Programming/UnrealArchitecture/StringHandling" +
            "/FString/index.html")]
        public string Logging_Document {
            get {
                return ((string)(this["Logging_Document"]));
            }
            set {
                this["Logging_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.unrealengine.com/en-US/Programming/UnrealArchitecture/Delegates/inde" +
            "x.html")]
        public string Delegate_Document {
            get {
                return ((string)(this["Delegate_Document"]));
            }
            set {
                this["Delegate_Document"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UPROPERTY_Template {
            get {
                return ((string)(this["UPROPERTY_Template"]));
            }
            set {
                this["UPROPERTY_Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UFUNCTION_Template {
            get {
                return ((string)(this["UFUNCTION_Template"]));
            }
            set {
                this["UFUNCTION_Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("      class UTemplateClass : public UObject\r\n      {\r\n        GENERATED_BODY()\r\n " +
            "     };")]
        public string UCLASS_Template {
            get {
                return ((string)(this["UCLASS_Template"]));
            }
            set {
                this["UCLASS_Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("      struct FTemplateStruct\r\n      {\r\n        GENERATED_BODY()\r\n      };")]
        public string USTRUCT_Template {
            get {
                return ((string)(this["USTRUCT_Template"]));
            }
            set {
                this["USTRUCT_Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("      enum class ETemplateEnum : uint8\r\n      {\r\n      \r\n      };")]
        public string UENUM_Template {
            get {
                return ((string)(this["UENUM_Template"]));
            }
            set {
                this["UENUM_Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("      class UTemprateInterface : public UInterface\r\n      {\r\n        GENERATED_BO" +
            "DY()\r\n      };\r\n\r\n      class ITemprateInterface\r\n      {\r\n        GENERATED_BOD" +
            "Y()\r\n      };")]
        public string UINTERFACE_Template {
            get {
                return ((string)(this["UINTERFACE_Template"]));
            }
            set {
                this["UINTERFACE_Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UMETA_Template {
            get {
                return ((string)(this["UMETA_Template"]));
            }
            set {
                this["UMETA_Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color MainColor {
            get {
                return ((global::System.Drawing.Color)(this["MainColor"]));
            }
            set {
                this["MainColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70, 70, 70")]
        public global::System.Drawing.Color BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TextColor {
            get {
                return ((global::System.Drawing.Color)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color LinkColor {
            get {
                return ((global::System.Drawing.Color)(this["LinkColor"]));
            }
            set {
                this["LinkColor"] = value;
            }
        }
    }
}
